### ISSUE TITLE
Add Support for Async Auth Flow

### ISSUE THREAD

**Issue by alexdlaird** [alexdlaird/amazon-orders-python#12]
Currently it's non-intuitive if someone doesn't want to use console input to answer OTP or Captcha questions. Add a way for them to pass their own lambda to `AuthForms` (still default to `input`), then document how this can be used.

**Comment by alexdlaird** [comment]
Actually, this would also work and be possible my extending `IODefault` and making your own implementation of `prompt` that.

**Comment by mkhazhinsky** [comment]
Could you please give an example of how an OTP prompt can be bypassed on console if the user can provide values programmatically?

**Comment by alexdlaird** [comment]
> Could you please give an example of how an OTP prompt can be bypassed on console if the user can provide values programmatically?

This wouldn't be possible with the out-of-the-box console interface. The integration tests [provide an example](https://github.com/alexdlaird/amazon-orders/blob/bda31a6ab0393b45cf42a0c745936d11e625727c/tests/integrationtestcase.py#L58) for how to do this in your own Python application though.

What is the need for bypass though? Perhaps you'd be better served explaining your use-case / the issue you're facing, so I can understand if there's a bug in the OTP flow that we need to resolve for CLI interactions.

**Comment by mkhazhinsky** [comment]
Thank you. To clarify, I would like to provide OTP code within my own python app. So, I will have an OTP code as a variable value and want to pass it. So, I was wondering if I can pass an OTP value directly to the form without experiencing a prompt on the console.

**Comment by alexdlaird** [comment]
> Thank you. To clarify, I would like to provide OTP code within my own python app. So, I will have an OTP code as a variable value and want to pass it. So, I was wondering if I can pass an OTP value directly to the form without experiencing a prompt on the console.

So then yes, basically do what the integration tests are doing. [Override `IODefault`](https://github.com/alexdlaird/amazon-orders/blob/bda31a6ab0393b45cf42a0c745936d11e625727c/amazonorders/session.py#L52), and provide your own implementation of `prompt` that doesn't issue an input to the console, pass that classes as `io` when you instantiate the `AmazonSession`.

**Comment by mkhazhinsky** [comment]
Thank you very much! It worked!
